### ISSUE TITLE
Please add me { DavidRomanovizc } to the triagers team

### ISSUE THREAD

**Issue by DavidRomanovizc** [aio-libs/triagers#21] opened 2023-04-28 14:46 UTC
**What's your background?**

Hello. I have been coding in Python for over 2.5 years and specialize in working with asynchronous libraries, such as Fast API and aiogram. I frequently developed API wrappers using aiohttp. Additionally, I have extensive knowledge in asyncio and understand the GIL, as well as how to utilize asyncio to free up resources. I am familiar with asyncpg and can execute multiple concurrent database queries. I also have experience working with multiprocessing and asyncio.

**What's your motivation?**

My motivation lies in personal development, helping developers, and improving my reputation. In other words, I want to improve my skills by working with different people and on a large codebase. Additionally, I want to contribute to the development of a library that I regularly use myself.

**Comment by Dreamsorcerer** [comment] 2023-04-28 15:49
Good with me. But, before closing any issues, please try to find a commit that shows the issue is fixed or provide information on why the issue is not relevant (as I have done following a couple of your comments).

Invite sent.

**Closed by Dreamsorcerer** 2023-04-28 15:49 UTC
Labels: help wanted
